name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Build with Maven
        run: mvn clean verify --file org.sbouchet.emn.fil1A/pom.xml
      
      - name: Deploy Maven Site to GitHub Pages
        run: mvn site --file org.sbouchet.emn.fil1A/pom.xml
      
      - name: Analyze with Sonar
        run: mvn sonar:sonar -Dsonar.organization=sbouchet-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN --file org.sbouchet.emn.fil1A/pom.xml
      
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        if: success()
        with:
          target_branch: gh-pages
          build_dir: org.sbouchet.emn.fil1A/target/site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
